#include "hq_base_db_model.h"
#include <QJsonObject>
#include <QJsonArray>
#include <QRegularExpression>
#include <QUuid>
#include <QDebug>
#include "hq_base.h"
#include "hq_base_db.h"

HQ_Base_Db_Model::HQ_Base_Db_Model()
{

}
/*================================================================
 * Return json string of model by given ModelName
 * Return "" on failed.
 * Format:
 * {
 *      "GUID":"value",
 *      "TableName":"value",
 *      "OrderBy":"value",
 *      "SqlBase":"value",
 *      "FK":"value",
 *      "AllColsWidthAuto":"value",
 *      "Fields":"fGUID|fParentID|fColOrder|fColText|...",//Used for saving
 *      "Cols":"fGUID|fParentID|fColOrder|fColText|...",//Used for displaying
 *      "Rows":[
 *          "fGUID":"value",
 *          "fParentID":"value",
 *          "fColOrder":"value",
 *          "fColText":"value",
 *          ...
 *      ]
 * }
 *
 * About Fields and Cols:
 *     Sometime they are different from each other, for saving and displaying.
 *     More desc in the part 'About Fields and Cols' at the first in header file
 *     'hq_base_db_model.h'.
 *===============================================================*/
QString HQ_Base_Db_Model::f_GetModel(QString sModelName, QString *sErr)
{
    QJsonObject oModel = f_GetModelAsJson(sModelName, sErr);
    if (oModel.isEmpty())
    {
        return "";
    }
    return HQ_Base::f_Json_ToString(oModel, sErr);
}
QJsonObject HQ_Base_Db_Model::f_GetModelAsJson(QString sModelName, QString *sErr)
{
    QJsonObject oModel;
    QString sErrPrefix = "Model info gotting failed.";

    //Get the main info of model, such as: TableName,OrderBy,...
    QString sSQL = QString("select * from t_Base_Model where fModelName='%1'").arg(sModelName);
    QJsonObject oJsonMain = HQ_Base_DB::f_GetQueryAsJsonObj(sSQL, sErr);
    if (oJsonMain.isEmpty())//if sql executed failed
    {
        return oModel;
    }

    QJsonArray arrMainRows = oJsonMain.value("Rows").toArray();
    if (arrMainRows.size() <= 0)//if no model
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + " For no row in the model.");
        return oModel;
    }

    QString sMainID             = arrMainRows.at(0).toObject().value("fGUID").toString().toLower();
    QString sTableName          = arrMainRows.at(0).toObject().value("fTable").toString();
    QString sViewName           = arrMainRows.at(0).toObject().value("fView").toString();
    QString sOrderBy            = arrMainRows.at(0).toObject().value("fOrderBy").toString();
    QString sSqlBase            = arrMainRows.at(0).toObject().value("fSqlBase").toString();
    QString sSqlWhere           = arrMainRows.at(0).toObject().value("fSqlWhere").toString();
    QString sFK                 = arrMainRows.at(0).toObject().value("fFK").toString();
    QString sAllColsWidthAuto   = arrMainRows.at(0).toObject().value("fAllColsWidthAuto").toString();
    QString sGridReadOnly       = arrMainRows.at(0).toObject().value("fGridReadOnly").toString();

    //Get the list of col info from database by table name.
    QStringList sFeildList;
    if (!sTableName.isEmpty())
    {
        sFeildList = HQ_Base_DB::f_GetFieldsListByTableName(sTableName, sErr);
        if (sFeildList.isEmpty())
        {
            HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix
                                  + QString(" For gotting fields list by table name failed.\n")
                                  + QString("The more desc is :\n1%").arg(HQ_Base::f_Pointer_GetValue(sErr)));
            return oModel;
        }
    }

    /* Get the col info of model.
     * Pay attention!!!
     * Because here, the sql statement is 'select * from t_Base_Model_Sub ...',
     * so the 'Cols' list is same to 'Fields' list.
     */
    sSQL = QString("select * from t_Base_Model_Sub where fParentID='%1' order by fColOrder").arg(sMainID);
    QJsonObject oJsonSub = HQ_Base_DB::f_GetQueryAsJsonObj(sSQL, sErr);
    if (oJsonSub.isEmpty())//if sql executed failed
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + " For sql executting failed");
        return oModel;
    }

    QJsonArray arrSubRows = oJsonSub.value("Rows").toArray();
    /* Nothing to do here, because the column info can be generated by f_GetColModel().
     *
     *     if (arrSubRows.size() <= 0)//if no column in model
     *     {
     *         HQ_Base::f_SetErrMessage(sErr, "There's no column in model.");
     *         return oModel;
     *     }
     */

    oModel.insert("GUID",               sMainID);
    oModel.insert("TableName",          sTableName);
    oModel.insert("ViewName",           sViewName);
    oModel.insert("OrderBy",            sOrderBy);
    oModel.insert("SqlBase",            sSqlBase);
    oModel.insert("SqlWhere",           sSqlWhere);
    oModel.insert("FK",                 sFK);
    oModel.insert("AllColsWidthAuto",   sAllColsWidthAuto);
    oModel.insert("GridReadOnly",       sGridReadOnly);
    oModel.insert("Fields",             sFeildList.join("|"));//Used for saving.
    oModel.insert("Cols",               oJsonSub.value("Cols").toString());//Used for displaying.

    oModel.insert("Rows", arrSubRows);

    HQ_Base::f_Pointer_SetValue(sErr, "");
    return oModel;
}
/*================================================================
 * Return a sql statement using to load grid, by given
 * ModelName and foreign key
 *===============================================================*/
QString HQ_Base_Db_Model::f_GetSqlByFk(QString sModelName,
                                       QString *sErr)
{
    return f_GetSqlByFk(sModelName, "", "", sErr);
}
QString HQ_Base_Db_Model::f_GetSqlByFk(QString sModelName,
                                       QString sFKvalue,
                                       QString *sErr)
{
    return f_GetSqlByFk(sModelName, "", sFKvalue, sErr);
}
QString HQ_Base_Db_Model::f_GetSqlByFk(QString sModelName,
                                       QString sWhere,
                                       QString sFKvalue,
                                       QString *sErr)
{
    QJsonObject oModel = f_GetModelAsJson(sModelName, sErr);
    return f_GetSqlByFk(oModel, sWhere, sFKvalue, sErr);
}
QString HQ_Base_Db_Model::f_GetSqlByFk(QJsonObject oModel,
                                       QString *sErr)
{
    return f_GetSqlByFk(oModel, "", "", sErr);
}
QString HQ_Base_Db_Model::f_GetSqlByFk(QJsonObject oModel,
                                       QString sFKvalue,
                                       QString *sErr)
{
    return f_GetSqlByFk(oModel, "", sFKvalue, sErr);
}
QString HQ_Base_Db_Model::f_GetSqlByFk(QJsonObject oModel,
                                       QString sWhere,
                                       QString sFKvalue,
                                       QString *sErr)
{
    QString sErrPrefix = "Sql gotting failed.";
    if (oModel.isEmpty())
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + " For the model gotting failed.");
        return "";
    }

    QString sTableName, sViewName, sOrderBy, sSQL_Base, sSQL_Where, sFK, sFK_Where;
    sTableName  = oModel.value("TableName").toString();
    sViewName   = oModel.value("ViewName").toString();
    sOrderBy    = oModel.value("OrderBy").toString();
    sSQL_Base   = oModel.value("SqlBase").toString();
    sSQL_Where  = oModel.value("SqlWhere").toString();
    sFK         = oModel.value("FK").toString();

    //table name or sql base.
    if (sViewName.isEmpty() && sSQL_Base.isEmpty())
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + " For the view name and the sql statement is all empty.");
        return "";
    }

    //The sql base statement
    if (sSQL_Base.isEmpty() && !sViewName.isEmpty())
    {
        sSQL_Base = QString("select * from %1").arg(sViewName);
    }

    //whether the sql contains where condition.
    bool bBaseHasWhere = (sSQL_Base.toLower().indexOf(" where ") > -1);

    //condition
    if(!sSQL_Where.isEmpty())
    {
        sSQL_Where = sSQL_Where.toLower().replace(QRegularExpression("^\\s*where\\s+"), "");
        if (!bBaseHasWhere)
        {
            sSQL_Where = QString(" where (%1)").arg(sSQL_Where);
        }
        else
        {
            sSQL_Where = QString(" and (%1)").arg(sSQL_Where);
        }
    }

    //the input sql condition
    if (!sWhere.isEmpty())
    {
        sWhere = sWhere.toLower().replace(QRegularExpression("^\\s*where\\s+"), "");
        if (!bBaseHasWhere && sSQL_Where.isEmpty())
        {
            sWhere = QString(" where (%1)").arg(sWhere);
        }
        else
        {
            sWhere = QString(" and (%1)").arg(sWhere);
        }
    }

    //fk
    if (!sFK.isEmpty() && !sFKvalue.isEmpty())
    {
        sFK_Where = QString("%1='%2'").arg(sFK).arg(sFKvalue);
        if (!bBaseHasWhere && sSQL_Where.isEmpty() && sWhere.isEmpty())
        {
            sFK_Where = QString(" where %1").arg(sFK_Where);
        }
        else
        {
            sFK_Where = QString(" and %1").arg(sFK_Where);
        }
    }

    //order by
    if (!sOrderBy.isEmpty())
    {
        sOrderBy = QString(" order by %1").arg(sOrderBy);
    }

    HQ_Base::f_Pointer_SetValue(sErr, "");
    return sSQL_Base + sSQL_Where + sWhere + sFK_Where + sOrderBy;
}
/*===============================================================
 * Return the model of columns(the rows of sub gird) as json array
 * by given sModelName of main gird.
 *
 *
 *===============================================================*/
QJsonArray HQ_Base_Db_Model::f_GetColModel(QString sModelName_Main, QString *sErr)
{
    QJsonArray oArr;
    QString sErrPrefix = "Cols info gotting failed.";

    //Get the model of main gird.
    QJsonObject oModel = f_GetModelAsJson(sModelName_Main, sErr);
    if (oModel.isEmpty())
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + QString(" For the model gotting failed.")
                              + QString("Try to save data at first.\n")
                              + QString("The more desc is: %1").arg(HQ_Base::f_Pointer_GetValue(sErr)));
        return oArr;
    }

    //Get the model of Base_Model_Sub.
    QJsonObject oModel_Base_Model_Sub = f_GetModelAsJson("Base_Model_Sub", sErr);
    if (oModel_Base_Model_Sub.isEmpty())
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix + QString(" For the Base_Model_Sub gotting failed.")
                              + QString("The more desc is: %1").arg(HQ_Base::f_Pointer_GetValue(sErr)));
        return oArr;
    }

    /* "Fields":"fGUID|fParentID|fColOrder|fColText|...",
     * "Cols":"fGUID|fParentID|fColOrder|fColText|...",
     * In the model string, they are same to each other. Using the FieldList is ok too.
     */
    //QStringList sColList = oModel_Base_Model_Sub.value("Fields").toString().split("|");
    QStringList sColList = oModel_Base_Model_Sub.value("Cols").toString().split("|");

    //Get SqlBase and table name.
    QString sSqlBase = oModel.value("SqlBase").toString();
    QString sTableName = oModel.value("TableName").toString();

    //Get the list of col from database, by sql or table name.
    QStringList sRowList;
    if (!sSqlBase.isEmpty())
    {
        //Get the list of col info from query by sqlbase statement.
        sRowList = HQ_Base_DB::f_GetColsListBySql(sSqlBase, sErr);
        if (sRowList.isEmpty())
        {
            HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix
                                  + QString("For gotting the fields list by SqlBase failed.\n")
                                  + QString("The more desc is :%1").arg(HQ_Base::f_Pointer_GetValue(sErr)));
            return oArr;
        }
    }
    else if (!sTableName.isEmpty())
    {
        //Get the list of col info from database by table name.
        sRowList = HQ_Base_DB::f_GetFieldsListByTableName(sTableName, sErr);
        if (sRowList.isEmpty())
        {
            HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix
                                  + QString(" For gotting the fields list by table name failed.\n")
                                  + QString("The more desc is :%1").arg(HQ_Base::f_Pointer_GetValue(sErr)));
            return oArr;
        }
    }
    else
    {
        if (sSqlBase.isEmpty() && sTableName.isEmpty())
        {
            HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix
                                  + " For the SqlBase and table name being both empty.");
            return oArr;
        }
    }

    //Get guid of model in main grid.
    QString sMainID = oModel.value("GUID").toString();
    QString sSQL = QString("delete from t_Base_Model_Sub where fParentID='%1'").arg(sMainID);

    //Delete the col info in sub grid.
    bool b = HQ_Base_DB::f_ExecSqlNoneQuery(sSQL, sErr);
    if (!b)
    {
        HQ_Base::f_Pointer_SetValue(sErr, sErrPrefix
                              + QString(" For the old col info deleting failed.")
                              + QString("The more desc is: %1").arg(HQ_Base::f_Pointer_GetValue(sErr)));
        return oArr;
    }

    //Made the col info to json array for adding to grid.
    for (int iRow = 0; iRow < sRowList.size(); iRow++)
    {
        QString sRowField = sRowList[iRow];
        QJsonObject oJsonRow;

        //"Cols":"fGUID|fParentID|fColOrder|fColText|...",
        for (int iCol = 0; iCol < sColList.size(); iCol++)
        {
            QString sField = sColList[iCol];
            QString sValue;
            if (sField == "fGUID")
            {
                /* Nothing to do, because the grid will generate the guid when it runs addRow().
                 * Such as below:
                 *
                 *     sValue = QUuid::createUuid().toString()
                 *             .toLower().replace("{", "").replace("}", "");
                 */
            }
            else if (sField == "fColOrder")
            {
                sValue = QString::number(iRow);
                /* If the order string is '*', change it to '0*'.
                 * It is required that the max count of fields is less than 100.
                 */
                if (sValue.length() < 2)
                {
                    sValue = QString("0%1").arg(sValue);
                }
            }
            else if (sField == "fColField")
            {
                sValue = sRowField;
            }
            else if (sField == "fColText")
            {
                //Delete the first char 'f', such as 'fField' to 'Field'.
                sValue = sRowField.mid(1);
            }
            else if (sField == "fColHidden")
            {
                sValue = "";
            }

            //{"fGUID":"value", "fParentID":"value", ...}
            oJsonRow.insert(sField, sValue);
        }
        oArr.append(oJsonRow);
    }

    HQ_Base::f_Pointer_SetValue(sErr, "");
    return oArr;
}
