/************************************************************************
 *  Class name:     HQ_Base_Db_Model
 *  Author:         NieXin
 *  Created date:   2022-5-20
 *  Used for:
 *
 *          Get data model from database and the data will be used to
 *      generate grid header. The data format is json string likes as
 *      below:
 *
 *          {
 *              "GUID":"value",
 *              "TableName":"value",
 *              "Cols":"fGUID|fParentID|fColOrder|fColText|...",
 *              "Rows":[
 *                  "fGUID":"value",
 *                  "fParentID":"value",
 *                  "fColOrder":"value",
 *                  "fColText":"value",
 *                  ...
 *              ]
 *          }
 *
 *          The data contains the info of grid columns, it'll be used
 *      to filling grid header.
 *
 *  Return value:   string
 *  Data carrier:   json string
 *  Data table:
 *
 *          In database, these two table named 't_Base_Model' and
 *      't_Base_Model_Sub' are necessary exist. And their name can not
 *      be changed. Or this code module can not working.
 *
 *  Usage method:
 *
 *      QString sModelMain = HQ_Base_Db_Model::f_get_Base_Model(sModelName);
 *      ui->oGridMain->f_FillHeader(sModelMain);
 *
 *      QString sSQL = HQ_Base_Db_Model::f_getSqlByFk(sModelName, "");
 *      QString sContents = HQ_Base_DB::f_getJsonStrBySql(sSQL, &sErr);
 *      ui->oGridMain->f_FillContents(sContents);
 *
 * About Fields and Cols:
 *
 *      "Fields":"fGUID|fParentID|fColOrder|fColText|...",//Used for saving
 *      "Cols":"fGUID|fParentID|fColOrder|fColText|...",//Used for displaying
 *
 *          These two keys 'Fields' and 'Cols', sometime they are different
 *      from each other, for saving and displaying.
 *
 *          The 'Cols' key was generated by querying from database. It used
 *      for displaying to ui. Cols can be different from fields saved in
 *      database.
 *
 *          The 'Fields' key was generated by given table name. It is same
 *      to the exactly fields in database. It used for saving data.
 *
 *          Sometime, you want to display to ui by some querying data. But
 *      the data was not from database table, and you do not want to save
 *      it  to  database  after  modified.  So  the  'Fields' key is very
 *      necessary.
 *
 *          For example, 'Col1' was generated from a query, it is a result
 *      of a computing, or a dynamic data for displaying. But it is not a
 *      field, so it can not be saved in database. So when the gird in ui
 *      was filling, the 'Cols' key was useful. When the gird was saving,
 *      the 'Field' key was useful. And the two keys 'Cols' and 'Fields'
 *      are different.
 *
 ************************************************************************/

#ifndef HQ_BASE_DB_MODEL_H
#define HQ_BASE_DB_MODEL_H

#include "qt-hq_base_global.h"
class QString;
class QJsonObject;
class QJsonArray;

class QTHQ_BASESHARED_EXPORT HQ_Base_Db_Model
{
public:
    HQ_Base_Db_Model();

    //Return json string of model by given ModelName.
    static QString f_GetModel(QString sModelName, QString *sErr = nullptr);

    //Return a sql statement using to load grid, by given ModelName and foreign key.
    static QString f_GetSqlByFk(QString sModelName,                                   QString *sErr = nullptr);
    static QString f_GetSqlByFk(QString sModelName,                 QString sFKvalue, QString *sErr = nullptr);
    static QString f_GetSqlByFk(QString sModelName, QString sWhere, QString sFKvalue, QString *sErr = nullptr);
    static QString f_GetSqlByFk(QJsonObject oModel,                                   QString *sErr = nullptr);
    static QString f_GetSqlByFk(QJsonObject oModel,                 QString sFKvalue, QString *sErr = nullptr);
    static QString f_GetSqlByFk(QJsonObject oModel, QString sWhere, QString sFKvalue, QString *sErr = nullptr);

    //Return the rows of sub gird as json array by given sModelName of main gird.
    static QJsonArray f_GetColModel(QString sModelName_Main, QString *sErr = nullptr);

private:
    //Return json object of model by given ModelName.
    static QJsonObject f_GetModelAsJson(QString sModelName, QString *sErr = nullptr);
};

#endif // HQ_BASE_DB_MODEL_H
